[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"
  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true